name = "getaway-sg-api"
main = "../apps/api/src/index.ts"
compatibility_date = "2024-08-01"
workers_dev = true

[vars]
API_PREFIX = "/api"

[[d1_databases]]
binding = "DB"
database_name = "getaway_sg_db"
database_id = "local-getaway-sg-db"

[[kv_namespaces]]
binding = "CACHE"
id = "local-cache"

## Queues disabled for current plan
# [[queues.producers]]
# binding = "ALERT_QUEUE"
# queue = "getaway-alerts"

[triggers]
crons = ["*/30 * * * *"] 

#[ Production environment ]
[env.production]
name = "getaway-sg-api"
main = "../apps/api/src/index.ts"
workers_dev = true

[env.production.vars]
API_PREFIX = "/api"

[[env.production.d1_databases]]
binding = "DB"
# Replace with your real production database
database_name = "getaway_sg_db"
database_id = "bd895f70-fb90-4b94-8a19-0bd95fdb21fc"

[[env.production.kv_namespaces]]
binding = "CACHE"
# Replace with your real KV namespace id
id = "0d3320effae0494ab0921b7d4d436f18"

## Queues disabled for current plan
# [[env.production.queues.producers]]
# binding = "ALERT_QUEUE"
# queue = "getaway-alerts"

# ci: trigger deploy-api workflow