name: Deploy API (Wrangler)

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/api/**'
      - 'infra/wrangler.toml'
      - '.github/workflows/deploy-api.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Build API
        run: pnpm --filter @getaway/api build

      - name: Deploy with Wrangler (production)
        run: pnpm --filter @getaway/api exec wrangler deploy --env production --config infra/wrangler.toml | cat
